
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/header/Header";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "next-themes";
import ThemeProviderWrapper from "@/components/header/ThemeProviderWrapper";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
     < ThemeProviderWrapper>
     <Header />
        <main>{children}</main>
        {/* {children} */}
        <Toaster />
        <Footer />
     </ThemeProviderWrapper>
       
        {/* </ThemeProvider> */}
        
      </body>
    </html>
  );
}
