export const darkColor = {
    primary: '#191919',
    secondary: '#222222',
    tertiary: '#b0b0b0',
    quaternary: '#dedede',
    quinary: '#f0f0f0',
}

export const employees = [
    {
      userId: "usr_1",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      avatar: "https://ui-avatars.com/api/?name=John+Doe",
      role: "admin",
      isVerified: true,
      createdAt: "2023-01-15T09:30:00Z",
    },
    {
      userId: "usr_2",
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      avatar: "https://ui-avatars.com/api/?name=Jane+Smith",
      role: "senior_employee",
      isVerified: true,
      createdAt: "2023-02-20T14:45:00Z",
    },
    {
      userId: "usr_3",
      firstName: "Robert",
      lastName: "Johnson",
      email: "robert.johnson@example.com",
      avatar: "https://ui-avatars.com/api/?name=Robert+Johnson",
      role: "assigned_employee",
      isVerified: false,
      createdAt: "2023-03-10T11:15:00Z",
    },
    {
      userId: "usr_4",
      firstName: "Emily",
      lastName: "Williams",
      email: "emily.williams@example.com",
      avatar: "https://ui-avatars.com/api/?name=Emily+Williams",
      role: "assigned_employee",
      isVerified: true,
      createdAt: "2023-04-05T16:20:00Z",
    },
    {
      userId: "usr_5",
      firstName: "Michael",
      lastName: "Brown",
      email: "michael.brown@example.com",
      avatar: "https://ui-avatars.com/api/?name=Michael+Brown",
      role: "senior_employee",
      isVerified: true,
      createdAt: "2023-05-12T10:00:00Z",
    },
    {
      userId: "usr_6",
      firstName: "Sarah",
      lastName: "Davis",
      email: "sarah.davis@example.com",
      avatar: "https://ui-avatars.com/api/?name=Sarah+Davis",
      role: "assigned_employee",
      isVerified: false,
      createdAt: "2023-06-18T13:30:00Z",
    },
    {
      userId: "usr_7",
      firstName: "David",
      lastName: "Miller",
      email: "david.miller@example.com",
      avatar: "https://ui-avatars.com/api/?name=David+Miller",
      role: "admin",
      isVerified: true,
      createdAt: "2023-07-22T09:45:00Z",
    },
    {
      userId: "usr_8",
      firstName: "Jessica",
      lastName: "Wilson",
      email: "jessica.wilson@example.com",
      avatar: "https://ui-avatars.com/api/?name=Jessica+Wilson",
      role: "assigned_employee",
      isVerified: true,
      createdAt: "2023-08-30T15:10:00Z",
    },
  ]