// dashboard/components/data.ts

export const softwareProducts = [
  {
    id: 1,
    name: "Adobe Creative Cloud",
    supplier: "Adobe Inc.",
    stock: 775,
    sales: 4858,
    batchTracked: "343454",
    icon: "🎨",
  },
  {
    id: 2,
    name: "Microsoft Office 365",
    supplier: "Microsoft Corp",
    stock: 888,
    sales: 1334,
    batchTracked: "5098923",
    icon: "📊",
  },
  {
    id: 3,
    name: "Zoom Pro",
    supplier: "Zoom Video Communications",
    stock: 466,
    sales: 7127,
    batchTracked: "3245672",
    icon: "🎥",
  },
  {
    id: 4,
    name: "Slack Enterprise",
    supplier: "Salesforce Inc.",
    stock: 722,
    sales: 2126,
    batchTracked: "3256477",
    icon: "💬",
  },
  {
    id: 5,
    name: "Google Workspace",
    supplier: "Google LLC",
    stock: 1200,
    sales: 5400,
    batchTracked: "987654",
    icon: "☁️",
  },
  {
    id: 6,
    name: "Adobe Photoshop",
    supplier: "Adobe Inc.",
    stock: 982,
    sales: 6142,
    batchTracked: "123987",
    icon: "🖌️",
  },
  {
    id: 7,
    name: "Trello Business Class",
    supplier: "Atlassian Inc.",
    stock: 540,
    sales: 3200,
    batchTracked: "4567890",
    icon: "📋",
  },
  {
    id: 8,
    name: "GitHub Enterprise",
    supplier: "Microsoft Corp.",
    stock: 670,
    sales: 4500,
    batchTracked: "7896543",
    icon: "🐙",
  },
];

export const dashboardMetrics = [
  {
    title: "Total Project",
    value: "22",
    change: 12,
    changeValue: "+3",
    changeLabel: "this week",
    trend: "up" as const,
    icon: "🛠️",
  },
  {
    title: "Total Employee",
    value: "58",
    change: 5,
    changeValue: "+3",
    changeLabel: "this month",
    trend: "up" as const,
    icon: "👨",
  },
  {
    title: "Total Sales",
    value: "$12,480",
    change: -1.2,
    changeValue: "-150",
    changeLabel: "this week",
    trend: "down" as const,
    icon: "💰",
  },
  {
    title: "Gross Profits",
    value: "$5,239",
    change: 14.4,
    changeValue: "+0.5k",
    changeLabel: "today",
    trend: "up" as const,
    icon: "💵",
  },
];